apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-simple-webserver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/AntonStefan/ci_cd_lab.git
    targetRevision: HEAD
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true              # Optional: remove resources no longer tracked in Git
      selfHeal: true           # Optional: fix out-of-sync resources automatically
    syncOptions:
      - CreateNamespace=true   # Optional: create namespace if it doesn't exist

